version: '3.1'
services:
  app:
    container_name: springboot-postgresql
    image: springboot-postgresql:latest
    build: ./
    ports:
      - "8000:8080"
    depends_on:
      - postgresqldb
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresqldb:5432/CodeCrafters
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=rabeb
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  postgresqldb:
    image: 'postgres:13.1-alpine'
    container_name: postgresqldb
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=rabeb
      - POSTGRES_USER=postgres
      - POSTGRES_DB=CodeCrafters
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgresqldb




